Fix for bad coding style issues
CUMSA/members pull request #25
Opened 2016-10-12 00:13 UTC by tanhanliang

The only problem is when updating internship details: the start and end dates show up as YYYY-MM-01 and the user has to manually delete '-01' before submitting. Still thinking of a solution to this.

2016-10-12 03:36 UTC, wonglkd requested changes
To solve your date format issue, I think you can do these things. I got this working on my localhost:
1. add `protected $dateFormat = 'Y-m'`, see Date Formats https://laravel.com/docs/5.3/eloquent-mutators
2. keep validation rules as `date|dateformat:Y-m`

I also changed the field type in `InternshipForm` to month but I think date works too.

In addition:

[InternlinkController.php#L218-L220](https://github.com/CUMSA/members/blob/3336d3d52124dd50d95e3e0bc87d7bad46baedcf/app/Http/Controllers/Internlink/InternlinkController.php#L218-L220)

```
        foreach($request['contact_options'] as $option){
            $link->$option = true;
        }
```

This shouldn't be required (bypassing fillable). I looked at `InternlinkSignupForm.php` and since they are stored as separate fields in the database, you could use [individual checkboxes](http://kristijanhusak.github.io/laravel-form-builder/field/checkbox-and-radio.html) (that way you get the saving/loading for free without extra code and you avoid the security risk mentioned).

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +            ]);
Unintentional space?

2016-10-12 03:36 UTC, wonglkd commented on database/factories/ModelFactory.php
>          'nric' => 'S9411885I',
I really hope that this isn't your real NRIC D:

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +        if(Auth::user()->member->internlink !== null){
You could replace lines 25-28 with `$link_exists = Auth::user()->member->internlink !== null;` since `!==` is an operator returning a boolean.

Since it is only used once, you could replace line 40 with:

```
            'link_exists' => Auth::user()->member->internlink !== null,
```

and reduce the need for someone reading the code to hunt for the definition of `$link_exists` (head looking up and down the file).

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +        $internship->link_id = Auth::user()->member->internlink->id;
https://laravel.com/docs/5.3/eloquent-relationships#inserting-and-updating-related-models

Eloquent has methods for dealing with relationships, you could consider something like:

`Auth::user()->member->internships()->save(new Internship($request->all());`

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +            'model' => Internship::where('id', $id)->get()->first(),
The current system allows users to edit each other's internships (try going to http://members.cumsa.org/internlink/myprofile/4 or 2 or 3).

One way to check this constraint might be to query `Auth::user()->member->internlink->internships()->find($id)` -- not sure that the chaining works - was reading [this post](https://laracasts.com/discuss/channels/general-discussion/eloquent-find-user-with-relation) and based it off that.

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +        if (Auth::user()->member->internlink === null) {
If this is already checked in `profile` which this function calls, do we need to check it in this function?

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +        $internships = Auth::user()->member->internlink->internship;
`Auth::user()->member->internlink->internship` or `Auth::user()->member->internlink->internships`? I thought Eloquent makes it plural if it's a `hasMany`, but I haven't tested.

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +        $link = Link::where('member_id', $member->id)->get()->first();
`$member->internlink`

2016-10-12 03:36 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +            $link->$option = true;
Taking user-supplied input to choose a variable name (without any form of whitelisting) is dangerous, as a malicious user could submit a contact_option called `member_id` or anything they want.

2016-10-12 03:36 UTC, wonglkd commented on resources/views/home.blade.php
> +                        <li><a href={{ route('internlink.profile.contact') }}>Edit InternLink profile</a></li>
UI-wise: it would be good to add a link to this on the InternLink page! It took me a while to figure out that I have to click on Home to update my InternLink profile.

Additionally, this link appears on the home page even if the user doesn't have an InternLink profile?

2016-10-20 01:06 UTC, tanhanliang commented on app/Http/Controllers/Internlink/InternlinkController.php
> +        if (Auth::user()->member->internlink === null) {
I didn't want an error page to appear if someone manually edited the URL. But then again, that is outside the normal range of expected behaviors so I think its OK.

2016-10-20 01:49 UTC, tanhanliang commented on app/Http/Controllers/Internlink/InternlinkController.php
> +        $internships = Auth::user()->member->internlink->internship;
internship works but I think internships is more informative

2016-10-20 01:54 UTC, tanhanliang commented on resources/views/home.blade.php
> +                        <li><a href={{ route('internlink.profile.contact') }}>Edit InternLink profile</a></li>
Yes it does, but redirects to the signup page if the user hasn't signed up yet

2016-10-20 02:06 UTC, wonglkd commented on resources/views/home.blade.php
> +                        <li><a href={{ route('internlink.profile.contact') }}>Edit InternLink profile</a></li>
Fair

2016-10-20 02:32 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
> +            ['link_id' => Auth::user()->member->internlink->id]
Hmm, is this required? The immediate smell is that `array_merge` probably shouldn't need to be used in a Laravel application (or most native PHP functions, actually). But the main thing here is that adding the Internship via internlink should automatically populate the `link_id` field:

https://laravel.com/docs/5.3/eloquent-relationships#the-save-method

> Notice that we did not access the comments relationship as a dynamic property. Instead, we called the comments method to obtain an instance of the relationship. **The save method will automatically add the appropriate post_id value to the new Comment model.**

2016-10-20 02:33 UTC, wonglkd commented on app/Http/Controllers/Internlink/InternlinkController.php
>          $link->resetContact();
I think that the entire function could be removed since it's now being populated automatically?

2016-10-20 02:34 UTC, wonglkd commented on app/Link.php
> +            'show_home_phone' => 'required_without_all:show_uk_phone,show_other_email,show_hermes_email',
Neat - didn't know you could do this (: good find.

2016-10-20 02:39 UTC, wonglkd commented on database/factories/ModelFactory.php
>          'nric' => 'S9411885I',
@tanhanliang maybe you could replace this with a fake NRIC? e.g. S1234567D

2016-10-20 02:40 UTC, wonglkd approved these changes

2016-10-20 02:41 UTC, wonglkd commented
Looks good to me! Please go ahead to merge once you address those comments (: thanks for your work!

2016-10-20 02:43 UTC, wonglkd commented on app/Link.php
> +}
Great in general to be consistent and to end lines with a newline (: See http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline for more discussion haha on that

2016-10-20 03:00 UTC, tanhanliang commented on app/Http/Controllers/Internlink/InternlinkController.php
>          $link->resetContact();
Oh yeah. Should have realised

2016-10-20 03:29 UTC, merged